CREATE OR REPLACE TABLE ORDER_DETAILS (
    ORDER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0),
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES STREAM_HACKATHON.STREAMLIT.CUSTOMER_DETAILS(CUSTOMER_ID)
);
