CREATE OR REPLACE TABLE PAYMENTS (
    PAYMENT_ID NUMBER(38,0) NOT NULL,
    ORDER_ID NUMBER(38,0),
    PAYMENT_DATE DATE,
    AMOUNT NUMBER(10,2),
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_DETAILS(ORDER_ID)
);
